### ISSUE TITLE
Possibility of creating a Windows DLL with chez-exe

### ISSUE THREAD

**Issue by ijacquez** [gwatt/chez-exe#11]
Before I go down this rabbit hole, would it be possible to create a DLL instead of an executable?

**Comment by gwatt** [comment]
Probably not in a way that would be useful. If you want to write a scheme library and have that automatically turned into a DLL where the exported library procedures are correctly set up for access from the C side, that's not possible. If you want to write a scheme library and manually craft a C wrapper around it, that's straightforward enough and would probably be simpler to avoid chez-exe altogether and instead link directly against the csv*.lib file.

**Comment by ijacquez** [comment]
Good point. Thanks for clarifying.
