### ISSUE TITLE
How do I find the location of petite-chez.a?

### ISSUE THREAD

**Issue by divs1210** [gwatt/chez-exe#14]
I'm seeing the following error:

```
$ ../chez-exe/compile-chez-program hello.ss            
compiling hello.ss with output to hello.so
clang: error: no such file or directory: '/usr/local/lib/petite-chez.a'
```

**Comment by gwatt** [comment]
Hey, the default location chez-exe looks for its libraries is `/usr/local/lib`, which is where they will be installed if you run `make install`. If you don't want to install chez-exe to system location you can manually specify `--chez-lib-dir /path/to/directory/containing/petite-chez.a` when running `compile-chez-program`. It looks like the path for the specific example you gave would be `--chez-lib-dir ../chez-exe`

**Comment by divs1210** [comment]
Thank you, I moved the `.a` files to `/usr/local/lib` and it works now.
Great tool, thanks for your work!
