### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by amirouche** [gwatt/chez-exe#2]
Are executable that `chez-exe` build static? ie. do they require chez installed to be able to execute the binary, similarly if I use a shared library (via chez ffi). Does chez-exe bundle the shared lib or it must be installed separately?

Is the build multi-platform? I not, is cross platform compilation possible?

TIA!

**Comment by amirouche** [comment]
Does it support stripping unsused procedures/modules?

**Comment by gwatt** [comment]
chez-exe produces self contained executables that do not require Chez Scheme be installed. (This is different from being statically linked.)
No bundling of C libraries is performed. Any external C libraries must be distributed separately from the executable.
The build is not multi-platform, and cross platform builds are not possible. You will need to compile chez-exe and then compile your program separately on each platform you wish to support.

chez-exe does nothing to eliminate dead code. However, it uses `compile-whole-program`: http://cisco.github.io/ChezScheme/csug9.5/system.html#./system:s68 Any optimizations Chez Scheme would normally perform will be done for the output of chez-exe.

**Comment by amirouche** [comment]
Tx!
