### ISSUE TITLE
Don't know how to make '"C:\chez\boot\ta6nt/csv95md.lib"'

### ISSUE THREAD

**Issue by anta40** [gwatt/chez-exe#3]
My laptop is running 64-bit Windows 10, and I have latest VS 2017 Community Edition installed.
I just built 64-bit, multithreaded Chez Scheme with these commands:

> env OS=Windows_NT ./configure -m=ta6nt
> env OS=Windows_NT make 

Then I copied the content of ta6nt directory into C:\chez. The next step is to build chez-exe. I put the source code at C:\chez\chez-exe and ran this:

> scheme.exe --script gen-config.ss --bootpath C:\chez\boot\ta6nt --scheme scheme.exe

When running **make.cmd**, I got this:

> C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdio.h(828): warning C4710: 'int fprintf(FILE *const ,const char *const ,...)': function not inlined
> C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdio.h(828): note: see declaration of 'fprintf'
>         "scheme.exe" --script make-boot-file.ss "C:\chez\boot\ta6nt"
>         "scheme.exe" --script build-included-binary-file.ss boot.generated.c chezschemebootfile boot
>         cl /nologo /Wall /I"C:\chez\boot\ta6nt" /DSCHEME_STATIC /DWIN32_LEAN_AND_MEAN /MD /c boot.generated.c
> boot.generated.c
> NMAKE : fatal error U1073: don't know how to make '"C:\chez\boot\ta6nt/csv95md.lib"'
> Stop.

I'm running those command via x64 Native Tools Command Prompt for VS 2017.

**Comment by gwatt** [comment]
Does the `C:\chez\boot` directory contain the file `csv95md.lib`?

**Comment by anta40** [comment]
There's no `csv95md.lib`. But there's `csv951md.lib`, which is located in `C:\chez\boot\ta6nt\`

**Comment by gwatt** [comment]
@anta40 Updated to use a wildcard for finding the csv.lib file instead of hard coding the version.
